# Generated by Django 3.1.6 on 2021-04-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=30)),
                ('currency_code', models.CharField(max_length=3)),
                ('currency_image', models.CharField(max_length=300)),
                ('currency_symbol', models.CharField(max_length=1)),
                ('currency_timestamp', models.IntegerField()),
                ('currency_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
