# Generated by Django 3.1.6 on 2021-04-28 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='currency_value',
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_rate',
            field=models.DecimalField(decimal_places=10, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
