# Generated by Django 3.1.6 on 2021-04-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210428_0742'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_code', models.CharField(max_length=3)),
                ('rate_timestamp', models.IntegerField(default=0)),
                ('rate_value', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
            ],
        ),
    ]
