# Generated by Django 3.1.6 on 2021-04-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate_timestamp',
            field=models.DateTimeField(),
        ),
    ]
