# Generated by Django 3.1.6 on 2021-05-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210428_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_symbol',
            field=models.CharField(max_length=3),
        ),
    ]
