# Generated by Django 3.1.7 on 2021-03-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_account_number_sender', models.CharField(max_length=20)),
                ('transaction_account_number_receiver', models.CharField(max_length=20)),
                ('transaction_id', models.CharField(max_length=20)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('transaction_currency', models.CharField(max_length=3)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
