# Generated by Django 3.1.7 on 2021-03-11 22:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_id',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_remain',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=7, validators=[django.core.validators.MinValueValidator(5.0)]),
            preserve_default=False,
        ),
    ]
