# Generated by Django 3.1.7 on 2021-03-11 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
        ('transaction_app', '0002_auto_20210311_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_account_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.profile'),
        ),
    ]
