# Generated by Django 3.1.7 on 2021-03-10 07:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app_account', '0002_auto_20210307_1149'),
        ('transaction_app', '0005_auto_20210307_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_description', models.CharField(max_length=20)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(5.0)])),
                ('loan_date', models.DateTimeField(auto_now_add=True)),
                ('loan_account_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_app_account.account')),
            ],
        ),
    ]
